const fs = require('fs');
const lines = fs.readFileSync('C:/minhviet-erp/src/App.jsx', 'utf8').split('\n');

const newApp = [
'export default function App(){',
'  const [currentUser, setCurrentUser] = React.useState(() => loadSession ? loadSession() : null);',
'  const [view, setView] = React.useState("dashboard");',
'  const [orders, setOrders] = React.useState(SEED_ORDERS);',
'  const [vouchers, setVouchers] = React.useState(SEED_VOUCHERS);',
'  const [expenses, setExpenses] = React.useState(SEED_EXPENSES);',
'  const [refunds, setRefunds] = React.useState(SEED_REFUNDS);',
'  const [customers, setCustomers] = React.useState(SEED_CUSTOMERS);',
'  const [userAccounts, setUserAccounts] = React.useState(USER_ACCOUNTS);',
'  const [quotes, setQuotes] = React.useState([]);',
'  const [tourPrograms, setTourPrograms] = React.useState(SEED_TOUR_PROGRAMS);',
'  const [bankAccounts, setBankAccounts] = React.useState(SEED_BANK_ACCOUNTS);',
'  const [personalTargets, setPersonalTargets] = React.useState(SEED_PERSONAL_TARGETS);',
'  const [outputInvoices, setOutputInvoices] = React.useState(SEED_OUTPUT_INVOICES);',
'  const [inputInvoices, setInputInvoices] = React.useState(SEED_INPUT_INVOICES);',
'  const [bookings, setBookings] = React.useState(SEED_NCC_BOOKINGS);',
'  const [credits, setCredits] = React.useState(SEED_CREDITS);',
'  const [notifs, setNotifs] = React.useState([]);',
'  const [hdvList, setHdvList] = React.useState([]);',
'  const [products, setProducts] = React.useState([]);',
'  const [careTasks, setCareTasks] = React.useState([]);',
'  const [msgHistory, setMsgHistory] = React.useState([]);',
'  const [deploySteps, setDeploySteps] = React.useState([]);',
'  const [approvalThreshold, setApprovalThreshold] = React.useState(20000000);',
'  const [showNotif, setShowNotif] = React.useState(false);',
'  const [showSearch, setShowSearch] = React.useState(false);',
'  const [selected, setSelected] = React.useState(null);',
'  const [showLogoutConfirm, setShowLogoutConfirm] = React.useState(false);',
'  const [toasts, setToasts] = React.useState([]);',
'',
'  const currentRole = currentUser?.role || "sale";',
'',
'  const pushToast = (msg, type="success") => {',
'    const id = Date.now()+Math.random();',
'    setToasts(t => [...t, {id, msg, type}]);',
'    setTimeout(() => setToasts(t => t.filter(x => x.id !== id)), 4000);',
'  };',
'  const pushNotif = (msg, type="success", extra={}) => {',
'    const id = Date.now()+Math.random();',
'    setNotifs(n => [{id, msg, type, time: new Date().toISOString(), read: false, ...extra}, ...n]);',
'    pushToast(msg, type);',
'  };',
'',
'  const handleLogin = (u) => { setCurrentUser(u); saveSession && saveSession(u); };',
'  const doLogout = () => { setCurrentUser(null); saveSession && saveSession(null); setShowLogoutConfirm(false); };',
'',
'  const handleCreateOrder = (data) => {',
'    const newId = "DH"+Date.now().toString().slice(-6);',
'    const newOrder = {...data, id:newId, createdAt:new Date().toISOString(), status:data.status||"pending_payment", totalPaid:data.depositAmount||0, auditLog:[{ts:new Date().toISOString(),by:currentUser?.name,action:"Tạo đơn hàng"}]};',
'    setOrders(p=>[newOrder,...p]);',
'    if(data.depositAmount>0){',
'      setVouchers(p=>[{id:"V"+Date.now(),orderId:newId,type:"thu",amount:data.depositAmount,method:"cash",note:"Tiền cọc khi tạo đơn",date:new Date().toISOString().slice(0,10),status:"approved",createdBy:currentUser?.name,createdAt:new Date().toISOString()},...p]);',
'    }',
'    pushNotif("Đã tạo đơn "+newId, "success");',
'    setView("orders");',
'  };',
'  const handleUpdateOrder = (updated) => { setOrders(p=>p.map(o=>o.id===updated.id?updated:o)); setSelected(updated); };',
'  const handleAddVoucher = (v) => setVouchers(p=>[v,...p]);',
'  const handleApprove = (id) => { setVouchers(vs=>vs.map(v=>v.id===id?{...v,status:"approved"}:v)); pushNotif("Đã duyệt phiếu "+id); };',
'  const handleReject = (id) => { setVouchers(vs=>vs.map(v=>v.id===id?{...v,status:"rejected"}:v)); pushNotif("Đã từ chối phiếu "+id,"error"); };',
'  const handleExpenseUpdate = (exp) => setExpenses(es=>es.map(x=>x.id===exp.id?exp:x));',
'  const handleCloseOrder = (o) => { setOrders(p=>p.map(x=>x.id===o.id?o:x)); setSelected(null); setView("closeorders"); };',
'  const handleRefundCreate = (r) => setRefunds(p=>[r,...p]);',
'  const handleRefundUpdate = (r) => setRefunds(p=>p.map(x=>x.id===r.id?r:x));',
'  const handleUpdateCurrentUser = (u) => { setCurrentUser(u); setUserAccounts(p=>p.map(x=>x.id===u.id?u:x)); saveSession && saveSession(u); };',
'',
'  const pendingApprovals = expenses.filter(e=>e.status==="pending").length + vouchers.filter(v=>v.status==="pending").length;',
'  const pendingRefunds = (refunds||[]).filter(r=>r.status==="pending").length;',
'  const pendingCare = (careTasks||[]).filter(t=>!t.done).length;',
'  const unreadCount = notifs.filter(n=>(!n.role||n.role===currentRole)&&!n.read).length;',
'',
'  if(!currentUser){',
'    return <LoginPage onLogin={handleLogin} userAccounts={userAccounts}/>;',
'  }',
'',
'  return (',
'    <AppShell',
'      sidebar={<Sidebar view={view} setView={setView} currentRole={currentRole} pendingApprovals={pendingApprovals} pendingRefunds={pendingRefunds} pendingCare={pendingCare}/>}',
'      topbar={<TopBar currentUser={currentUser} currentRole={currentRole} unreadCount={unreadCount} onNotif={()=>setShowNotif(v=>!v)} onSearch={()=>setShowSearch(true)} onProfile={()=>setView("profile")} onLogout={()=>setShowLogoutConfirm(true)}/>}',
'    >',
'      {view==="dashboard"&&currentRole==="manager"&&<DirectorDashboard orders={orders} vouchers={vouchers} expenses={expenses} personalTargets={personalTargets} onUpdateTargets={setPersonalTargets} userAccounts={userAccounts} customers={customers}/>}',
'      {view==="dashboard"&&(currentRole==="accountant"||currentRole==="cashier")&&<AccountantDashboard orders={orders} vouchers={vouchers} expenses={expenses} refunds={refunds} bankAccounts={bankAccounts}/>}',
'      {view==="dashboard"&&(currentRole==="sale"||currentRole==="dieu_hanh")&&<SaleDashboard currentUser={currentUser} orders={orders} vouchers={vouchers} personalTargets={personalTargets}/>}',
'',
'      {view==="orders"&&<OrderList orders={orders} vouchers={vouchers} onView={o=>{setSelected(o);setView("detail");}} onCreate={()=>setView("create")} currentRole={currentRole} currentUser={currentUser}/>}',
'      {view==="create"&&<OrderForm onSave={handleCreateOrder} onCancel={()=>setView("orders")} pushNotif={pushToast} defaultSale={currentUser.name} currentRole={currentRole} customers={customers} onCreateCustomer={()=>setView("crm")} tourPrograms={tourPrograms}/>}',
'      {view==="detail"&&selected&&<OrderDetail order={selected} vouchers={vouchers} expenses={expenses} onBack={()=>setView("orders")} onUpdate={handleUpdateOrder} onAddVoucher={handleAddVoucher} onApprove={handleApprove} onReject={handleReject} pushNotif={pushToast} currentRole={currentRole} bankAccounts={bankAccounts} currentUser={currentUser} hdvList={hdvList} credits={credits} onUpdateCredits={setCredits}/>}',
'',
'      {view==="crm"&&<CrmModule orders={orders} pushNotif={pushToast} customers={customers} onUpdateCustomers={setCustomers} currentUser={currentUser} msgHistory={msgHistory} onLogMessage={rec=>setMsgHistory(h=>[rec,...h].slice(0,500))} onCreateOrderFromLead={()=>setView("create")}/>}',
'      {view==="tourops"&&<TourOpsModule orders={orders} pushNotif={pushToast} currentUser={currentUser} currentRole={currentRole} hdvList={hdvList}/>}',
'      {view==="tourprogram"&&<TourProgramModule tourPrograms={tourPrograms} onUpdate={setTourPrograms} currentRole={currentRole} pushNotif={pushToast} currentUser={currentUser}/>}',
'      {view==="hdv"&&<HDVModule hdvList={hdvList} onUpdate={setHdvList} orders={orders} pushNotif={pushToast} currentRole={currentRole}/>}',
'      {view==="quotes"&&<QuoteModule quotes={quotes} onUpdate={setQuotes} orders={orders} tourPrograms={tourPrograms} currentUser={currentUser} pushNotif={pushToast} onCreateOrder={(data)=>{handleCreateOrder(data);}}/>}',
'      {view==="accounting"&&<AccountantDashboard orders={orders} vouchers={vouchers} expenses={expenses} refunds={refunds} bankAccounts={bankAccounts}/>}',
'      {view==="ncc"&&<NCCDashboard orders={orders} vouchers={vouchers} pushNotif={pushToast} currentRole={currentRole} currentUser={currentUser} bookings={bookings} onUpdateBookings={setBookings} onCreateExpense={(exp)=>{setExpenses(p=>[exp,...p]);pushToast("Phiếu chi "+exp.id+" chờ KT duyệt","warning");}}/>}',
'      {view==="approvals"&&<ApprovalsModule orders={orders} expenses={expenses} onExpenseUpdate={handleExpenseUpdate} pushNotif={pushToast} currentRole={currentRole} currentUser={currentUser} approvalThreshold={approvalThreshold}/>}',
'      {view==="refunds"&&<RefundModule orders={orders} vouchers={vouchers} refunds={refunds} onRefundUpdate={handleRefundUpdate} onRefundCreate={handleRefundCreate} pushNotif={pushToast} currentRole={currentRole} currentUser={currentUser}/>}',
'      {view==="credits"&&<CreditModule orders={orders} pushNotif={pushToast} credits={credits} onUpdateCredits={setCredits}/>}',
'      {view==="closeorders"&&<CloseOrderModule orders={orders} vouchers={vouchers} expenses={expenses} refunds={refunds} onCloseOrder={handleCloseOrder} pushNotif={pushToast} currentRole={currentRole} currentUser={currentUser}/>}',
'      {view==="users"&&currentRole==="manager"&&<UserManagementPage userAccounts={userAccounts} onUpdateAccounts={setUserAccounts} currentUser={currentUser} pushNotif={pushToast} personalTargets={personalTargets} onUpdateTargets={setPersonalTargets} approvalThreshold={approvalThreshold} onUpdateThreshold={setApprovalThreshold}/>}',
'      {view==="reports"&&<ReportModule orders={orders} vouchers={vouchers} expenses={expenses} personalTargets={personalTargets} currentRole={currentRole} hdvList={hdvList}/>}',
'      {view==="tourghep"&&<TourGhepModule products={products} onUpdate={setProducts} orders={orders} currentRole={currentRole} currentUser={currentUser} pushNotif={pushToast} onCreateOrder={(data)=>handleCreateOrder(data)}/>}',
'      {view==="aftercare"&&<AfterSaleModule careTasks={careTasks} onUpdateTasks={setCareTasks} orders={orders} customers={customers} currentUser={currentUser} currentRole={currentRole} pushNotif={pushToast}/>}',
'      {view==="deploy"&&currentRole==="manager"&&<DeployPanel deploySteps={deploySteps} onUpdateSteps={setDeploySteps}/>}',
'      {view==="profile"&&<ProfilePage currentUser={currentUser} onUpdate={handleUpdateCurrentUser} onBack={()=>setView("dashboard")} pushNotif={pushToast}/>}',
'      {view==="banks"&&<BankAccountModule bankAccounts={bankAccounts} onUpdate={setBankAccounts} pushNotif={pushToast}/>}',
'',
'      {showLogoutConfirm&&(',
'        <div style={{position:"fixed",inset:0,background:"rgba(0,0,0,.4)",zIndex:2000,display:"flex",alignItems:"center",justifyContent:"center"}} onClick={e=>e.target===e.currentTarget&&setShowLogoutConfirm(false)}>',
'          <div style={{background:"#fff",borderRadius:16,padding:28,width:360,textAlign:"center"}}>',
'            <div style={{fontSize:32,marginBottom:12}}>🚪</div>',
'            <div style={{fontWeight:700,fontSize:16,marginBottom:8}}>Đăng xuất khỏi hệ thống?</div>',
'            <div style={{fontSize:13,color:"#64748b",marginBottom:20}}>Bạn sẽ cần đăng nhập lại để tiếp tục sử dụng.</div>',
'            <div style={{display:"flex",gap:10}}>',
'              <button onClick={doLogout} style={{flex:1,background:"#ef4444",color:"#fff",border:"none",borderRadius:10,padding:11,cursor:"pointer",fontWeight:700}}>Đăng xuất</button>',
'              <button onClick={()=>setShowLogoutConfirm(false)} style={{flex:1,background:"#f1f5f9",border:"none",borderRadius:10,padding:11,cursor:"pointer",fontWeight:600}}>Hủy</button>',
'            </div>',
'          </div>',
'        </div>',
'      )}',
'',
'      {toasts.map(t => (',
'        <div key={t.id} style={{position:"fixed",bottom:24,right:24,background:t.type==="error"?"#ef4444":"#22c55e",color:"#fff",padding:"12px 20px",borderRadius:8,zIndex:9999,boxShadow:"0 4px 16px rgba(0,0,0,.2)"}}>',
'          {t.msg}',
'        </div>',
'      ))}',
'    </AppShell>',
'  );',
'}',
].join('\n');

let appStart = -1;
for(let i=0;i<lines.length;i++){ if(/^export default function App\(\)/.test(lines[i])) { appStart=i; break; } }
console.log('App starts at line', appStart+1, 'of', lines.length);
lines.splice(appStart, lines.length-appStart, ...newApp.split('\n'));
fs.writeFileSync('C:/minhviet-erp/src/App.jsx', lines.join('\n'), 'utf8');
console.log('New file length:', lines.length);
