export const SERVICES = [
  { id:"ve_may_bay",        label:"Vé máy bay",          icon:"✈"  },
  { id:"tour",              label:"Tour trọn gói",        icon:"🗺"  },
  { id:"tour_ghep_nd",      label:"Tour ghép nội địa",   icon:"🚌"  },
  { id:"tour_ghep_qt",      label:"Tour ghép quốc tế",   icon:"🌏"  },
  { id:"cruise",            label:"Du thuyền",            icon:"🚢"  },
  { id:"hotel_flight",      label:"Combo KS+Vé",         icon:"🏨"  },
  { id:"ve_tham_quan",      label:"Vé tham quan",        icon:"🎟"  },
  { id:"khach_san",         label:"Khách sạn",            icon:"🏩"  },
  { id:"visa",              label:"Visa",                 icon:"🛂"  },
  { id:"bao_hiem",          label:"Bảo hiểm du lịch",    icon:"🛡"  },
  { id:"thue_xe",           label:"Thuê xe",              icon:"🚗"  },
  { id:"mice_teambuilding", label:"MICE / Teambuilding",  icon:"🎯"  },
];

export const COST_GROUPS = [
  { id:"transport",  label:"Vận chuyển",    icon:"🚌" },
  { id:"hotel",      label:"Lưu trú",       icon:"🏨" },
  { id:"food",       label:"Ăn uống",       icon:"🍽" },
  { id:"sightseeing",label:"Tham quan",     icon:"🎟" },
  { id:"guide",      label:"HDV & Nhân sự", icon:"👤" },
  { id:"event",      label:"Sự kiện / MICE",icon:"🎭" },
  { id:"accessory",  label:"Phụ kiện",      icon:"🎁" },
  { id:"other",      label:"Chi phí khác",  icon:"💰" },
];

export const CHECKLIST_TEMPLATES = {
  ve_may_bay: [
    { id:"c1",  phase:"Ngay sau xuất vé",   label:"Kiểm tra thông tin vé (tên, ngày, chặng, hạng vé)", req:true  },
    { id:"c2",  phase:"Ngay sau xuất vé",   label:"Gửi vé cho khách (Zalo/Facebook/Email/SMS)",        req:true  },
    { id:"c3",  phase:"Ngay sau xuất vé",   label:"Khách xác nhận đã nhận vé",                         req:true  },
    { id:"c4",  phase:"Ngay sau xuất vé",   label:"Nhập mã booking (PNR) vào đơn",                    req:true  },
    { id:"c5",  phase:"Trước ngày bay",     label:"Check-in online cho khách (cửa sổ 2h–24h trước bay)", req:true },
    { id:"c6",  phase:"Trước ngày bay",     label:"Nhắc khách mang CCCD/Hộ chiếu bản gốc",            req:true  },
    { id:"c7",  phase:"Trước ngày bay",     label:"Xác nhận hành lý (nếu khách có yêu cầu ký gửi)",   req:false },
    { id:"c8",  phase:"Ngày bay",           label:"Nhắc giờ có mặt sân bay (nội địa 1.5–2h, QT 3h)",  req:true  },
    { id:"c9",  phase:"Ngày bay",           label:"Xác nhận khách đã check-in thành công",              req:false },
    { id:"c10", phase:"Chiều về (khứ hồi)", label:"Check-in online chiều về",                           req:false },
    { id:"c11", phase:"Chiều về (khứ hồi)", label:"Nhắc giờ có mặt sân bay chiều về",                  req:false },
    { id:"c12", phase:"Thông tin transit",  label:"Ghi rõ thời gian nối chuyến + sân bay trung chuyển",req:false },
    { id:"c13", phase:"Thông tin transit",  label:"Nhắc khách không ra khỏi khu vực transit",           req:false },
  ],
  tour: [
    { id:"t1",  phase:"D-7 Chuẩn bị",    label:"Danh sách đoàn đủ CCCD/Hộ chiếu",                    req:true  },
    { id:"t2",  phase:"D-7 Chuẩn bị",    label:"Confirm khách sạn (voucher đã nhận)",                 req:true  },
    { id:"t3",  phase:"D-7 Chuẩn bị",    label:"Confirm xe (biển số, tài xế, SĐT)",                   req:true  },
    { id:"t4",  phase:"D-7 Chuẩn bị",    label:"Briefing HDV (lịch trình, yêu cầu đặc biệt)",         req:true  },
    { id:"t5",  phase:"D-7 Chuẩn bị",    label:"Thanh toán NCC đủ chưa",                              req:true  },
    { id:"t6",  phase:"D-7 Chuẩn bị",    label:"Kiểm tra vé tham quan/entry fee các điểm",            req:false },
    { id:"t7",  phase:"D-1 Nhắc khách",  label:"Gửi lịch trình chi tiết cho khách",                   req:true  },
    { id:"t8",  phase:"D-1 Nhắc khách",  label:"Nhắc giờ tập trung + địa điểm + cách đi",             req:true  },
    { id:"t9",  phase:"D-1 Nhắc khách",  label:"HDV xác nhận sẵn sàng",                               req:true  },
    { id:"t10", phase:"Ngày khởi hành",  label:"Điểm danh đủ khách",                                   req:true  },
    { id:"t11", phase:"Ngày khởi hành",  label:"Phát tài liệu/mũ/phụ kiện tour",                      req:false },
    { id:"t12", phase:"Ngày khởi hành",  label:"Khởi hành đúng giờ",                                  req:true  },
    { id:"t13", phase:"Trong tour",      label:"Check-in khách sạn OK (số phòng đã cấp)",              req:true  },
    { id:"t14", phase:"Trong tour",      label:"Các điểm tham quan theo đúng lịch trình",              req:false },
    { id:"t15", phase:"Kết thúc tour",   label:"Toàn bộ khách về an toàn",                             req:true  },
    { id:"t16", phase:"Kết thúc tour",   label:"Quyết toán HDV",                                       req:true  },
    { id:"t17", phase:"Kết thúc tour",   label:"Thu feedback từ khách",                                req:false },
  ],
  cruise: [
    { id:"cr1",  phase:"Chuẩn bị",       label:"Xác định loại tàu (tàu ngày / tàu đêm)",               req:true  },
    { id:"cr2",  phase:"Chuẩn bị",       label:"Confirm cảng đón + giờ check-in tàu",                  req:true  },
    { id:"cr3",  phase:"Chuẩn bị",       label:"Gửi danh sách khách + CCCD cho tàu",                   req:true  },
    { id:"cr4",  phase:"Chuẩn bị",       label:"Thanh toán đủ theo deadline tàu quy định",             req:true  },
    { id:"cr5",  phase:"Chuẩn bị",       label:"[Tàu đêm] Confirm cabin (số phòng, loại phòng)",       req:false },
    { id:"cr6",  phase:"Chuẩn bị",       label:"Xác nhận meal plan + activities đã included",          req:true  },
    { id:"cr7",  phase:"Chuẩn bị",       label:"Ghi nhận yêu cầu đặc biệt (ăn chay, dị ứng...)",       req:false },
    { id:"cr8",  phase:"D-1 Nhắc khách", label:"Nhắc điểm tập trung + giờ (trước 30 phút)",            req:true  },
    { id:"cr9",  phase:"D-1 Nhắc khách", label:"Nhắc mang CCCD bản gốc",                               req:true  },
    { id:"cr10", phase:"Ngày đi",        label:"Xác nhận khách đã lên tàu đầy đủ",                     req:true  },
    { id:"cr11", phase:"Kết thúc",       label:"Xác nhận khách về an toàn",                             req:true  },
    { id:"cr12", phase:"Kết thúc",       label:"Quyết toán với tàu",                                    req:true  },
  ],
  tour_ghep_nd: [
    { id:"tg1", phase:"D-7 Confirm",    label:"Gửi danh sách khách cho đơn vị tổ chức",               req:true  },
    { id:"tg2", phase:"D-7 Confirm",    label:"Nhận xác nhận chỗ từ đơn vị tổ chức",                  req:true  },
    { id:"tg3", phase:"D-7 Confirm",    label:"Xác nhận điểm đón + giờ đón chính xác",                req:true  },
    { id:"tg4", phase:"D-7 Confirm",    label:"Lấy SĐT đầu mối bên đơn vị tổ chức",                   req:true  },
    { id:"tg5", phase:"D-7 Confirm",    label:"Thanh toán cho đơn vị tổ chức",                        req:true  },
    { id:"tg6", phase:"D-1 Nhắc khách",label:"Nhắc khách điểm đón + giờ đón",                         req:true  },
    { id:"tg7", phase:"D-1 Nhắc khách",label:"Gửi SĐT đầu mối/HDV cho khách liên lạc",               req:true  },
    { id:"tg8", phase:"Kết thúc",       label:"Xác nhận khách về an toàn",                             req:true  },
    { id:"tg9", phase:"Kết thúc",       label:"Thu feedback",                                          req:false },
  ],
  ve_tham_quan: [
    { id:"vt1", phase:"Đặt vé",  label:"Xác nhận loại vé (NL/TE/combo) + số lượng",            req:true  },
    { id:"vt2", phase:"Đặt vé",  label:"Xác nhận ngày sử dụng + giờ vào (nếu có slot)",        req:true  },
    { id:"vt3", phase:"Đặt vé",  label:"Thanh toán + nhận vé (giấy hoặc điện tử)",             req:true  },
    { id:"vt4", phase:"Đặt vé",  label:"Ghi nhận hạn sử dụng vé",                              req:true  },
    { id:"vt5", phase:"Giao vé", label:"Gửi vé cho khách (ảnh chụp/file PDF/QR code)",         req:true  },
    { id:"vt6", phase:"Giao vé", label:"Khách xác nhận đã nhận vé",                            req:true  },
    { id:"vt7", phase:"Nhắc nhở",label:"Nhắc khách ngày sử dụng vé + giờ vào",                 req:false },
  ],
  khach_san: [
    { id:"ks1", phase:"Đặt phòng",      label:"Confirm booking (voucher KS đã nhận)",                  req:true  },
    { id:"ks2", phase:"Đặt phòng",      label:"Xác nhận loại phòng, tên đặt, số đêm",                 req:true  },
    { id:"ks3", phase:"Đặt phòng",      label:"Breakfast included? Ghi rõ",                           req:true  },
    { id:"ks4", phase:"Đặt phòng",      label:"Cọc NCC: đã thanh toán chưa + deadline còn lại",       req:true  },
    { id:"ks5", phase:"Trước check-in", label:"Gửi voucher KS cho khách",                             req:true  },
    { id:"ks6", phase:"Trước check-in", label:"Nhắc giờ check-in (standard 14h, early nếu có)",       req:true  },
    { id:"ks7", phase:"Trước check-in", label:"Xác nhận early check-in / late check-out nếu cần",     req:false },
    { id:"ks8", phase:"Sau check-in",   label:"Khách check-in thành công",                            req:true  },
    { id:"ks9", phase:"Checkout",       label:"Khách checkout OK + không phát sinh",                   req:false },
  ],
  visa: [
    { id:"v1",  phase:"Nhận hồ sơ",label:"Nhận đủ hồ sơ từ khách (passport, ảnh, form...)",      req:true  },
    { id:"v2",  phase:"Nhận hồ sơ",label:"Kiểm tra hộ chiếu còn hạn đủ 6 tháng",                 req:true  },
    { id:"v3",  phase:"Nộp hồ sơ", label:"Nộp hồ sơ cho công ty dịch vụ visa",                   req:true  },
    { id:"v4",  phase:"Nộp hồ sơ", label:"Ghi nhận ngày nộp + ngày nhận dự kiến",                req:true  },
    { id:"v5",  phase:"Theo dõi",  label:"Theo dõi trạng thái hồ sơ",                             req:true  },
    { id:"v6",  phase:"Nhận visa", label:"Nhận visa từ công ty dịch vụ",                          req:true  },
    { id:"v7",  phase:"Nhận visa", label:"Kiểm tra thông tin visa (tên, ngày, loại)",              req:true  },
    { id:"v8",  phase:"Giao khách",label:"Gửi/giao visa cho khách",                               req:true  },
    { id:"v9",  phase:"Giao khách",label:"Khách xác nhận đã nhận",                                req:true  },
  ],
  bao_hiem: [
    { id:"bh1", phase:"Phát hành",label:"Chọn đối tác (MIC / PTI-DBV)",                          req:true  },
    { id:"bh2", phase:"Phát hành",label:"Xác nhận gói bảo hiểm + quyền lợi",                    req:true  },
    { id:"bh3", phase:"Phát hành",label:"Thu thập thông tin khách (tên, CCCD, ngày sinh)",       req:true  },
    { id:"bh4", phase:"Phát hành",label:"Phát hành hợp đồng/thẻ bảo hiểm",                      req:true  },
    { id:"bh5", phase:"Phát hành",label:"Ghi nhận số hợp đồng + ngày hiệu lực → hết hạn",       req:true  },
    { id:"bh6", phase:"Giao khách",label:"Gửi hợp đồng/thẻ BH cho khách",                        req:true  },
    { id:"bh7", phase:"Giao khách",label:"Thông báo số hotline claim cho khách",                  req:true  },
    { id:"bh8", phase:"Giao khách",label:"Khách xác nhận đã nhận",                                req:true  },
  ],
  thue_xe: [
    { id:"tx1", phase:"Đặt xe",        label:"Xác nhận loại xe + số chỗ",             req:true  },
    { id:"tx2", phase:"Đặt xe",        label:"Confirm tài xế (tên + SĐT)",             req:true  },
    { id:"tx3", phase:"Đặt xe",        label:"Biển số xe",                            req:true  },
    { id:"tx4", phase:"Đặt xe",        label:"Giờ đón + địa điểm đón chính xác",      req:true  },
    { id:"tx5", phase:"Đặt xe",        label:"Lộ trình + điểm trả cuối",              req:true  },
    { id:"tx6", phase:"Đặt xe",        label:"Thanh toán (cọc + còn lại khi nào)",    req:true  },
    { id:"tx7", phase:"Nhắc khách",    label:"Gửi thông tin xe + tài xế cho khách",   req:true  },
    { id:"tx8", phase:"Ngày thực hiện",label:"Xác nhận xe đón đúng giờ",              req:true  },
    { id:"tx9", phase:"Hoàn thành",    label:"Khách về an toàn + thanh toán đủ",       req:true  },
  ],
  mice_teambuilding: [
    { id:"m1",  phase:"Khởi động",    label:"Xác nhận số lượng người tham dự chính thức",           req:true  },
    { id:"m2",  phase:"Khởi động",    label:"Confirm địa điểm tổ chức (voucher/hợp đồng)",          req:true  },
    { id:"m3",  phase:"Khởi động",    label:"Chương trình activities đã duyệt",                     req:true  },
    { id:"m4",  phase:"Khởi động",    label:"Catering/tiệc đã confirm (menu, số suất)",             req:true  },
    { id:"m5",  phase:"Khởi động",    label:"Thiết bị (âm thanh, ánh sáng, backdrop, máy chiếu...)",req:true },
    { id:"m6",  phase:"Khởi động",    label:"Nhân sự MC/Trainer/Facilitator đã confirm",            req:true  },
    { id:"m7",  phase:"Khởi động",    label:"Thanh toán NCC các hạng mục",                          req:true  },
    { id:"m8",  phase:"Chuẩn bị",     label:"Danh sách đoàn gửi cho địa điểm",                      req:true  },
    { id:"m9",  phase:"Chuẩn bị",     label:"In ấn: tên bảng, backdrop, tài liệu...",               req:false },
    { id:"m10", phase:"Chuẩn bị",     label:"Quà tặng/phần thưởng đã chuẩn bị",                    req:false },
    { id:"m11", phase:"D-1 Chạy thử", label:"Chạy thử chương trình + setup địa điểm",              req:true  },
    { id:"m12", phase:"D-1 Chạy thử", label:"Kiểm tra thiết bị âm thanh/ánh sáng",                 req:true  },
    { id:"m13", phase:"D-1 Chạy thử", label:"Confirm lại toàn bộ nhân sự",                          req:true  },
    { id:"m14", phase:"Ngày sự kiện", label:"Check-in đoàn",                                        req:true  },
    { id:"m15", phase:"Ngày sự kiện", label:"Chương trình diễn ra đúng kế hoạch",                   req:true  },
    { id:"m16", phase:"Ngày sự kiện", label:"Xử lý phát sinh (nếu có)",                             req:false },
    { id:"m17", phase:"Kết thúc",     label:"Quyết toán tất cả NCC",                                req:true  },
    { id:"m18", phase:"Kết thúc",     label:"Thu feedback từ khách hàng",                           req:true  },
  ],
};

// Tour ghép quốc tế = checklist tour ghép nội địa
CHECKLIST_TEMPLATES.tour_ghep_qt = CHECKLIST_TEMPLATES.tour_ghep_nd;
// Combo = KS + vé máy bay
CHECKLIST_TEMPLATES.hotel_flight = [
  ...CHECKLIST_TEMPLATES.ve_may_bay.map(c => ({...c, id:"hf_v_"+c.id})),
  ...CHECKLIST_TEMPLATES.khach_san.map(c  => ({...c, id:"hf_k_"+c.id})),
];
